<?php
/**
 * @file
 * Farm weather module.
 */

/**
 * Implements hook_help().
 */
function farm_weather_help($path, $arg) {

  // Add help text to the weather quick form.
  if ($path == 'farm/quick/weather') {
    return '<p>' . t('Use this form to record an observed weather event. An observation log will be created with standard details filled in. You may use this form repeatedly to record multiple weather events in a single day.') . '</p>';
  }
}

/**
 * Implements hook_farm_log_categories().
 */
function farm_weather_farm_log_categories() {

  // Provide an "Weather" log category.
  return array('Weather');
}
